@startuml
start
:initViews();
:initData();
:initFragment();
:changeUI(status);
:registerReceiver();
:loadVideo();
if(loacalPath == null)then(true)
    :sdkPresenter.initComp(castId, isTraining);
    :initParam;
    :new VodSite(act);
    :vodSite.setVodListener();
    :vodSite.getVodObject(initParam);
    if(点播数据初始化调用回调) then(成功)
        :OnVodListener.onVodObject();
        :onChatHistory()...;
        if(onliveStutas) then(true)
            :initPlayer();
            if(loacalPath !=null) then(true)
                :player.play(loacalPath,this,"");
            else(false)
                :player.play(vodId, this, "");
            endif
        else(false)
            :do nothing;
        endif
    else (失败)
        :OnVodListener.onVodErr();
    endif
else(no)
    :sdkPresenter.setLoacalPath(loacalPath);
    :sdkPresenter.initPlayer();
endif
:init VideoFloatFragment && ViewPager;
if(onStart():onlyLandScape) then(true)
    :return;
else(no)
    :initOrientationEventListener;
endif
:onResume():setVideoLiveStatus();
:onStop():setVideoLiveStatus(isLive);
:onDestroy():unregisterReceiver()、sdkPresenter.release()、onDestroyView();

stop
@enduml