@startuml

class SoftKeyboardSizeWatchLayout{
    监听屏幕高度变化
    得到软键盘高度
    int mScreenHeight = 0;
    boolean mIsSoftKeyboardPop = false;
}

interface OnResizeListener {
   void OnSoftPop(int height);
   void OnSoftClose();
}

abstract class AutoHeightLayout{
    protected int mMaxParentHeight;
    protected int mSoftKeyboardHeight;
    onMeasure();
    abstract void onSoftKeyboardHeightChanged(int height);
}

class XhsEmoticonsKeyBoard{
    inflateKeyboardBar();
    initFuncView();
    addFuncView(View view);
    reset();
}

interface OnEmoticonsPageViewListener {
    void emoticonSetChanged();
    void playTo();
    void playBy();
}

interface OnToolBarItemClickListener {
   void onToolBarItemClick(PageSetEntity pageSetEntity);
}

interface OnBackKeyClickListener {
    定义在EmoticonsEditText
    void onBackKeyClick();
}

interface OnFuncChangeListener {
   void onFuncChange(int key);
}

class UserdefEmoticonsKeyBoard{
}

class FuncLayout{
    int DEF_KEY;
    int mHeight;
    SparseArray<View> mFuncViewArrayMap;
    void addFuncView(int key, View view);
    void hideAllFuncView();
    toggleFuncView();//软键盘开关
}


class EmoticonsEditText{
    List<EmoticonFilter> mFilterList;
    onTextChanged();
    emoticonFilter.filter();
}


class EmoticonsFuncView{
    PageSetAdapter mPageSetAdapter;
    int mCurrentPagePosition;
    void setAdapter(PageSetAdapter adapter);
    setOnPageChangeListener();
    setCurrentPageSet();
}

class EmoticonsIndicatorView{
    Drawable mDrawableSelect;
    Drawable mDrawableNomal;
    playTo();
    playBy();
    updateIndicatorCount(int count)
}

class EmoticonsToolBarView{
    ArrayList<View> mToolBtnList;
    int mBtnWidth;
    HorizontalScrollView hsv_toolbar;
    addToolItemView();
    scrollToBtnPosition();
}

abstract class EmoticonFilter{
    abstract void filter();
    getDrawableFromAssets();
    getDrawable();
}

class DefFilter{
    filter();
    //在输入框中显示表情
    emoticonDisplay();
}

class AnimEmoticonsIndicatorView{
    playTo();
    playBy();
}

class SimpleCommonUtils{
    initEmoticonsEditText();
    PageSetAdapter getCommonAdapter();
}

interface EmoticonClickListener<T> {
    void onEmoticonClick();
}


SoftKeyboardSizeWatchLayout -up-|> RelativeLayout
AutoHeightLayout -up-|> SoftKeyboardSizeWatchLayout
AutoHeightLayout .up.|> OnResizeListener
XhsEmoticonsKeyBoard -up-|> AutoHeightLayout
XhsEmoticonsKeyBoard ..|> OnEmoticonsPageViewListener
XhsEmoticonsKeyBoard ..|> OnToolBarItemClickListener
XhsEmoticonsKeyBoard ..|> OnBackKeyClickListener
XhsEmoticonsKeyBoard ..|> OnFuncChangeListener
UserdefEmoticonsKeyBoard -up-|> XhsEmoticonsKeyBoard
EmoticonsIndicatorView <|-- AnimEmoticonsIndicatorView

LinearLayout <|-- FuncLayout
EditText <|-- EmoticonsEditText
ViewPager <|-- EmoticonsFuncView
LinearLayout <|-- EmoticonsIndicatorView
RelativeLayout <-- EmoticonsToolBarView
EmoticonFilter <|-- DefFilter

@enduml